export enum ProviderCategory {
  DNS_PROVIDER = "DNS_PROVIDER",
  CDN_PROXY = "CDN_PROXY",
  EMAIL_PROVIDER = "EMAIL_PROVIDER",
  CRM = "CRM",
  MARKETING_AUTOMATION = "MARKETING_AUTOMATION",
  SSO_IDP = "SSO_IDP",
  ANALYTICS = "ANALYTICS",
  OTHER_SAAS = "OTHER_SAAS",
}
